language: node_js
node_js:
- '6'
install:
- yarn install
env:
- TEST_DIR=server
script:
- cd $TEST_DIR
- npm test
- npm run report-coverage
after_success:
- cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js